/**
 * auto-seed.ts
 * Called automatically when a product is created or updated in the admin.
 * Seeds ProductCityPage rows for all approved product × city combos.
 * Never overwrites manually edited content (isAutoGenerated = false).
 */

import prisma from '@/lib/prisma';
import {
  isApprovedForCityPages,
  TOP_CITIES_FOR_PRODUCT_PAGES,
  CITY_DELIVERY_ESTIMATES,
  getCityBySlug,
} from './city-data';

interface ProductInfo {
  slug: string;
  name: string;
  description: string;
  price: number;
  salePrice?: number | null;
  lightReq: string;
  waterReq?: string | null;
  careLevel: string;
}

/** City-specific care tips for known plant × city combos */
const CITY_CARE_OVERRIDES: Record<string, Record<string, string>> = {
  'money-plant': {
    bengaluru: 'Bengaluru\'s mild, humid climate is perfect for Money Plants. Water every 7–10 days and keep near a bright window — avoid the afternoon sun on south-facing balconies.',
    delhi:     'Delhi summers are harsh. Move your Money Plant indoors from May–August and water every 5–7 days. The plant thrives in Delhi\'s cool winters with minimal care.',
    mumbai:    'Mumbai\'s high humidity means Money Plants can go 10–12 days between waterings. Avoid overwatering during the June–September monsoon season.',
    pune:      'Pune\'s pleasant climate suits Money Plants year-round. Water every 8–10 days. The dry winters (Nov–Feb) may require slightly more frequent watering.',
    chennai:   'Chennai\'s heat and humidity mean your Money Plant will grow quickly. Water every 5–7 days and ensure good drainage to prevent root rot in the humid weather.',
  },
  'snake-plant': {
    bengaluru: 'Snake Plants thrive in Bengaluru\'s 18–28°C range. Water sparingly — every 2–3 weeks. Perfect for Bengaluru apartments with indirect light.',
    delhi:     'Snake Plants are ideal for Delhi homes. They handle Delhi\'s extreme temperatures well. Water every 2–3 weeks; even less in Delhi\'s dry winters.',
    mumbai:    'Mumbai humidity can cause overwatering issues with Snake Plants. Water once every 3 weeks and ensure the pot has drainage holes.',
    pune:      'Pune\'s dry winters and warm summers suit Snake Plants well. Water every 2–3 weeks and place near a window for best results.',
    chennai:   'In Chennai\'s heat, Snake Plants act as natural air purifiers. Water every 2 weeks and keep out of direct afternoon sun.',
  },
  'peace-lily': {
    bengaluru: 'Peace Lilies love Bengaluru\'s cool, humid climate. Water once a week and keep away from direct sunlight — ideal for Bengaluru offices and living rooms.',
    delhi:     'In Delhi, Peace Lilies need more frequent watering in summer (every 5–6 days) and less in winter (every 10 days). Keep away from ACs and heaters.',
    mumbai:    'Mumbai\'s humidity is perfect for Peace Lilies. Water when the top inch of soil feels dry. They thrive in Mumbai\'s high-rise apartments with indirect light.',
    pune:      'Peace Lilies do well in Pune\'s moderate climate. Water every 7–8 days and mist the leaves occasionally during Pune\'s dry season.',
    chennai:   'Keep Peace Lilies indoors in Chennai — they prefer temperatures below 30°C. Water twice a week and ensure good ventilation.',
  },
  'areca-palm': {
    bengaluru: 'Areca Palms are a top choice for Bengaluru homes. The city\'s 20–28°C climate is ideal. Water every 5–7 days and place near a bright, indirect light source.',
    delhi:     'In Delhi, Areca Palms need protection from temperatures below 10°C in winter. Water every 5–7 days and mist leaves during dry Delhi winters.',
    mumbai:    'Areca Palms thrive in Mumbai\'s tropical climate. Water every 5–7 days. Reduce watering during monsoon. Great for Mumbai balconies and living rooms.',
    pune:      'Pune\'s comfortable temperatures suit Areca Palms perfectly. Water every 6–8 days and fertilise monthly during the growing season.',
    chennai:   'Chennai\'s year-round warmth is ideal for Areca Palms. Water every 5–6 days. Great air purifier for Chennai\'s urban spaces.',
  },
};

function generateCareTip(product: ProductInfo, citySlug: string): string {
  const override = CITY_CARE_OVERRIDES[product.slug]?.[citySlug];
  if (override) return override;

  const city = getCityBySlug(citySlug);
  const cityName = city?.cityName ?? citySlug;
  const lightMap: Record<string, string> = {
    LOW: 'low indirect light — perfect for indoor corners',
    MEDIUM: 'bright indirect light near a window',
    HIGH: 'direct or very bright indirect light',
  };
  const lightText = lightMap[product.lightReq] ?? 'indirect light';
  const waterText = product.waterReq
    ? `water ${product.waterReq.toLowerCase()}`
    : 'water when the top inch of soil feels dry';

  return `${product.name} grows well in ${cityName}'s climate. Place it in ${lightText} and ${waterText}. ${cityName}'s temperature range suits this plant for year-round indoor display.`;
}

function generateH1(productName: string, cityName: string): string {
  return `Buy ${productName} Online in ${cityName} — Fresh Delivery`;
}

function generateMetaTitle(productName: string, cityName: string, price: number): string {
  return `Buy ${productName} in ${cityName} — Rs ${price} Free Delivery | IndoorPlant.in`;
}

function generateMetaDesc(product: ProductInfo, cityName: string, deliveryEstimate: string): string {
  const price = product.salePrice ?? product.price;
  return `Get ${product.name} delivered fresh in ${cityName} in ${deliveryEstimate}. Starting at Rs ${price}. Expert-packed, damage-protected delivery. AI plant care advice included.`;
}

/**
 * Called from the admin product save action.
 * Idempotent — safe to call on every product update.
 */
export async function onProductSaved(product: ProductInfo): Promise<void> {
  if (!isApprovedForCityPages(product.slug)) return;

  const upsertOps = TOP_CITIES_FOR_PRODUCT_PAGES.map((citySlug) => {
    const city = getCityBySlug(citySlug);
    const cityName = city?.cityName ?? citySlug;
    const deliveryEstimate = CITY_DELIVERY_ESTIMATES[citySlug] ?? '3–5 business days';
    const price = product.salePrice ?? product.price;

    const defaults = {
      metaTitle:    generateMetaTitle(product.name, cityName, price),
      metaDesc:     generateMetaDesc(product, cityName, deliveryEstimate),
      h1:           generateH1(product.name, cityName),
      localCareTip: generateCareTip(product, citySlug),
      deliveryNote: `Delivered in ${deliveryEstimate} across ${cityName}`,
      isAutoGenerated: true,
      isActive: true,
      isIndexed: true,
    };

    return prisma.productCityPage.upsert({
      where: { productSlug_citySlug: { productSlug: product.slug, citySlug } },
      create: { productSlug: product.slug, citySlug, ...defaults },
      // Only update auto-generated records — never overwrite manually edited content
      update: {
        metaTitle:    { set: defaults.metaTitle },
        metaDesc:     { set: defaults.metaDesc },
        h1:           { set: defaults.h1 },
        localCareTip: { set: defaults.localCareTip },
        deliveryNote: { set: defaults.deliveryNote },
      },
    });
  });

  await Promise.all(upsertOps);

  // Revalidate all affected city pages so Next.js cache is cleared
  const { revalidatePath } = await import('next/cache');
  for (const citySlug of TOP_CITIES_FOR_PRODUCT_PAGES) {
    revalidatePath(`/shop/${product.slug}/${citySlug}`);
  }
}
