import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { revalidatePath } from 'next/cache';

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const productSlug = searchParams.get('product');
  const citySlug = searchParams.get('city');

  const pages = await prisma.productCityPage.findMany({
    where: {
      ...(productSlug ? { productSlug } : {}),
      ...(citySlug ? { citySlug } : {}),
    },
    orderBy: [{ productSlug: 'asc' }, { citySlug: 'asc' }],
  });
  return NextResponse.json(pages);
}

export async function PATCH(req: NextRequest) {
  const body = await req.json();
  const { productSlug, citySlug, ...data } = body;
  if (!productSlug || !citySlug) {
    return NextResponse.json({ error: 'productSlug and citySlug required' }, { status: 400 });
  }

  const page = await prisma.productCityPage.update({
    where: { productSlug_citySlug: { productSlug, citySlug } },
    data: { ...data, isAutoGenerated: false }, // mark as manually edited
  });

  revalidatePath(`/shop/${productSlug}/${citySlug}`);
  return NextResponse.json(page);
}
